##############################################################################
#
# GitGub CI workflow syntax spec:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# Coveralls example:
#    https://github.com/marketplace/actions/coveralls-github-action
#
##############################################################################

name: Build

on:
  # Triggered whenever push to the master branch
  push:
    branches: [ "master" ]

  # Triggered whenever a pull request is created on master
  pull_request:
    branches: [ "master" ]
    types: [opened]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-20.04
    
    steps:
      # We want to use GitHub CI checkout version 3 for checking out the branch
      - uses: actions/checkout@v3
      
    # Install some system pacakges
          - name: Install ROS 2 Galactic packages
            run: |
              locale  
              sudo apt update && sudo apt install locales
              sudo locale-gen en_US en_US.UTF-8
              sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
              export LANG=en_US.UTF-8
              locale  

              sudo apt install software-properties-common
              sudo add-apt-repository universe

              sudo apt update && sudo apt install curl
              sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
              
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

              sudo apt update
              sudo apt upgrade

              sudo apt install -y ros-galactic-ros-base python3-colcon-common-extensions

              sudo apt install ros-dev-tools
              source /opt/ros/galactic/setup.bash

              sudo apt install -y lcov
        
      # Build for test coverage
      - name: Building package
        run: 
          source /opt/ros/galactic/setup.bash
          colcon build --packages-select inspection-robot
          
      # Run CMake to setup compilation flags
      # - name: Configure Coverage CMake 
        # run: cmake -D COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -B ${{github.workspace}}/build 
      
      # Compile and executables
      # - name: Build Coverage
      #   working-directory: ${{github.workspace}}/build
      #   run: cmake

      # Run test suite and compute code coverage
      # - name: Run Test Coverage
      #   working-directory: ${{github.workspace}}/build
      #   run: make code_coverage
      
      # Upload coverage result to Coverage.io 
      # - name: Upload result to Coveralls.io
      #   uses: coverallsapp/github-action@1.1.3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: ${{github.workspace}}/build/coverage.info.cleane
